create table sensor(
    id int primary key generated by default as identity,
    name varchar(100) not null unique
);

create table measurement(
    id int primary key generated by default as identity,
    value double precision not null,
    raining boolean not null,
    measurement_date_time timestamp not null,
    sensor varchar(100) references sensor(name)

);